# Copyright (c) 2017, Peter K. G. Williams.
#
# This file is part of Dedalus, which is free software distributed
# under the terms of the GPLv3 license.  A copy of the license should
# have been included in the file 'LICENSE.txt', and is also available
# online at <http://www.gnu.org/licenses/gpl-3.0.html>.

# This is a fairly straightforward rebundling of conda-forge's mpi4py recipe,
# except that it uses `system-mpi-libs` rather than the bundled `mpich`. We
# only build this package if `use_system_mpi` is 1, since otherwise we can
# just use the conda-forge version.

{% set name = "mpi4py" %}
{% set version = "2.0.0" %}
{% set build_number = "0" %}
{% set build_string = "ded" %}
{% set sha256 = "6543a05851a7aa1e6d165e673d422ba24e45c41e4221f0993fe1e5924a00cb81" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  string: {{ build_number }}{{ build_string }}

requirements:
  build:
    - python
    - pip
    - system-mpi-libs
  run:
    - python
    - system-mpi-libs

test:
  imports:
    - mpi4py
    - mpi4py.MPI

about:
  home: http://pythonhosted.org/mpi4py/
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Provides bindings of the MPI standard for Python
  description: |
     MPI for Python provides bindings of the Message Passing Interface (MPI)
     standard for the Python programming language, allowing any Python program
     to exploit multiple processors.
  doc_url: http://mpi4py.readthedocs.org/
  dev_url: https://bitbucket.org/mpi4py/mpi4py
