# Copyright (c) 2017, Peter K. G. Williams.
#
# This file is part of Dedalus, which is free software distributed
# under the terms of the GPLv3 license.  A copy of the license should
# have been included in the file 'LICENSE.txt', and is also available
# online at <http://www.gnu.org/licenses/gpl-3.0.html>.

# This is a fairly straight copy of the conda-forge build script for fftw,
# modified to build MPI versions as well. We also don't bother with the
# static libraries.

{% set name = "fftw" %}
{% set version = "3.3.6" %}
{% set build_number = "0" %}
{% set build_string = "ded" %}
{% set sha256 = "a5de35c5c824a78a058ca54278c706cdf3d4abba1c56b63531c2cb05f5d57da2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.fftw.org/fftw-{{ version }}-pl2.tar.gz
  sha256: {{ sha256 }}
  patches:
    - mpilibs.patch

build:
  number: {{ build_number }}
  string: {{ build_number }}{{ build_string }}

requirements:
  build:
    - perl 5.22.2.1
{% if use_system_mpi != '0' %}
    - system-mpi-libs
{% else %}
    - mpich
{% endif %}
  run:
{% if use_system_mpi != '0' %}
    - system-mpi-libs
{% else %}
    - mpich
{% endif %}

test:
  commands:
    # Verify headers are installed
    - test -f ${PREFIX}/include/fftw3.h                  # [not win]
    - test -f ${PREFIX}/include/fftw3-mpi.h              # [not win]

    # Verify shared libraries are installed
    {% set fftw_libs = [
            "libfftw3",
            "libfftw3_threads",
            "libfftw3_mpi",
            "libfftw3f",
            "libfftw3f_threads",
            "libfftw3f_mpi",
            "libfftw3l",
            "libfftw3l_threads",
            "libfftw3l_mpi",
    ] %}

    {% for lib in fftw_libs %}
    - test -f ${PREFIX}/lib/{{ lib }}.dylib    # [osx]
    - test -f ${PREFIX}/lib/{{ lib }}.so       # [linux]
    {% endfor %}

about:
  home: http://fftw.org
  license: GPL 2
  summary: "The fastest Fourier transform in the west, plus MPI!"
