# Copyright (c) 2017, Peter K. G. Williams.
#
# This file is part of Dedalus, which is free software distributed
# under the terms of the GPLv3 license.  A copy of the license should
# have been included in the file 'LICENSE.txt', and is also available
# online at <http://www.gnu.org/licenses/gpl-3.0.html>.

# This package provides files in $PREFIX/lib that symlink to the system's MPI
# installation. We do this because conda-build strips out rpaths that point to
# non-system locations from the binaries it creates, so we need to pretend
# that we're linking to local libraries.

{% set name = "system-mpi-libs" %}
{% set version = "0.1" %}
{% set build_number = "0" %}
{% set build_string = "ded" %}
{% set sha256 = "f0132c1a34408eae6353f01145220450aa8cbaaccfd99223479ef43133ea4eaf" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: empty-test-tarball-1.0.2.tgz
  url: https://registry.npmjs.org/empty-test-tarball/-/empty-test-tarball-1.0.2.tgz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  string: {{ build_number }}{{ build_string }}
  script_env:
    - DEDALUS_BUILDER_SETUP

requirements:
  build:
  run:

about:
  home: http://dedalus-project.org/
  license: GPLv3
  license_family: GPL
  summary: Relocatable references to the system MPI implementation.
