# Copyright (c) 2017, Peter K. G. Williams.
#
# This file is part of Dedalus, which is free software distributed
# under the terms of the GPLv3 license.  A copy of the license should
# have been included in the file 'LICENSE.txt', and is also available
# online at <http://www.gnu.org/licenses/gpl-3.0.html>.

{% set name = "dedalus" %}
{% set version = "20170920" %}
{% set build_number = "0" %}
{% set build_string = "ded" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  hg_url: https://bitbucket.org/kburns/dedalus # XXX
  hg_tag: 760173997220 # XXX "cardinal" bookmark; symbolic name doesn't work
  patches:
    - install-tools.patch

build:
  number: {{ build_number }}
  string: {{ build_number }}{{ build_string }}
  script_env:
    - DEDALUS_BUILDER_SETUP

requirements:
  build:
    - cython
    - docopt
    - fftw
    - h5py
    - matplotlib
    - mpi4py
    - numpy
    - pathlib
    - python >=3
    - scipy
  run:
    - cython
    - docopt
    - fftw
    - h5py
    - matplotlib
    - mpi4py
    - numpy
    - pathlib
    - python >=3
    - scipy

tests:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
  imports:
    - dedalus.public

about:
  home: http://dedalus-project.org/
  license: GPLv3
  summary: PDEs
